HomeWork-WebUI/HomeWork-WebUI/Riode.WebUI/Areas/Admin/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Riodetask.Model.DataContexts;
using Riodetask.Model.Entity;

namespace Riodetask.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AllowAnonymous]
    public class BlogPostsController : Controller
    {
        readonly RioDbContext db;
        readonly IWebHostEnvironment env;

        public BlogPostsController(RioDbContext db , IWebHostEnvironment env)
        {
            this.db = db;
            this.env = env;
        }

        // GET: Admin/BlogPosts
        public async Task<IActionResult> Index()
        {
            return View(await db.BlogPosts
                .Where(b => b.PublishDate == null && b.DeleteByUserId==null)
                .OrderByDescending(b=>b.ID)
                .ToListAsync());
        }

        // GET: Admin/BlogPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await db.BlogPosts
                .FirstOrDefaultAsync(m => m.ID == id);
            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // GET: Admin/BlogPosts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( BlogPost blogPost, IFormFile file)
        {
            if (file == null)
            {
                ModelState.AddModelError("file", "File secilmeyib");
            }
            if (ModelState.IsValid)
            {

                string extension = Path.GetExtension(file.FileName);
                blogPost.ImagePath = $"{Guid.NewGuid()}{extension}";
                string pyschialFileName = Path.Combine(env.ContentRootPath,
                    "wwwroot",
                    "uploads",
                    "images",
                    "blog",
                     blogPost.ImagePath);
                using (var stream = new FileStream(pyschialFileName,FileMode.Create,FileAccess.Write))
                {
                    await file.CopyToAsync(stream);
                }

                db.Add(blogPost);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blogPost);
        }

        // GET: Admin/BlogPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {


            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await db.BlogPosts.FindAsync(id);
            if (blogPost == null)
            {
                return NotFound();
            }
            return View(blogPost);
        }

        // POST: Admin/BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BlogPost blogPost, IFormFile file, string fileTemp)
        {
            if (string.IsNullOrEmpty(fileTemp) && file == null)
            {
                ModelState.AddModelError("file", "Shekil secilmeyib");
            }
            
            if (id != blogPost.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var entity = await db.BlogPosts.FirstOrDefaultAsync(b => b.ID == id && b.DeleteByUserId==null);
                    entity.Title = blogPost.Title;
                    entity.Body = blogPost.Body;
                    if (file !=null)
                    {
                        string extension = Path.GetExtension(file.FileName);
                        blogPost.ImagePath = $"{Guid.NewGuid()}{extension}";
                        string pyschialFileName = Path.Combine(env.ContentRootPath,
                            "wwwroot",
                            "uploads",
                            "images",
                            "blog",
                             blogPost.ImagePath);
                        using (var stream = new FileStream(pyschialFileName, FileMode.Create, FileAccess.Write))
                        {
                            await file.CopyToAsync(stream);
                        }
                        if (!string.IsNullOrWhiteSpace(entity.ImagePath))
                        {
                            System.IO.File.Delete(Path.Combine(env.ContentRootPath, 
                                "wwwroot",
                                "uploads",
                                "images",
                                "blog",
                                entity.ImagePath));
                        }
                        entity.ImagePath = blogPost.ImagePath;
                    }
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogPostExists(blogPost.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blogPost);
        }

        // GET: Admin/BlogPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await db.BlogPosts
                .FirstOrDefaultAsync(m => m.ID == id);
            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // POST: Admin/BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blogPost = await db.BlogPosts.FindAsync(id);
            db.BlogPosts.Remove(blogPost);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogPostExists(int id)
        {
            return db.BlogPosts.Any(e => e.ID == id);
        }
    }
}

HomeWork-WebUI/HomeWork-WebUI/Riode.WebUI/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Riodetask.Model.DataContexts;
using Riodetask.Model.Entity;

namespace Riodetask.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriesController : Controller
    {
        private readonly RioDbContext db;

        public CategoriesController(RioDbContext db)
        {
            this.db = db;
        }

        // GET: Admin/Categories
        public async Task<IActionResult> Index()
        {
            var rioDbContext = db.Categories
                .Include(c => c.Children)
                .ThenInclude(c => c.Children)
                .Where(c => c.ParentID == null && c.DeleteByUserId == null);

            return View(await rioDbContext.ToListAsync());
        }

        // GET: Admin/Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await db.Categories
                .Include(c => c.Parent)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/Categories/Create
        public IActionResult Create()
        {
            ViewData["ParentID"] = new SelectList(db.Categories, "ID", "Name");
            return View();
        }

        // POST: Admin/Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ParentID,Name,Description,ID,CreatedByUserId,CreatedTime,DeleteByUserId,DeletedTime")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Add(category);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentID"] = new SelectList(db.Categories, "ID", "Description", category.ParentID);
            return View(category);
        }

        // GET: Admin/Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await db.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            ViewData["ParentID"] = new SelectList(db.Categories, "ID", "Description", category.ParentID);
            return View(category);
        }

        // POST: Admin/Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ParentID,Name,Description,ID,CreatedByUserId,CreatedTime,DeleteByUserId,DeletedTime")] Category category)
        {
            if (id != category.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(category);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentID"] = new SelectList(db.Categories, "ID", "Description", category.ParentID);
            return View(category);
        }

        // GET: Admin/Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await db.Categories
                .Include(c => c.Parent)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await db.Categories.FindAsync(id);
            db.Categories.Remove(category);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return db.Categories.Any(e => e.ID == id);
        }
    }
}

HomeWork-WebUI/HomeWork-WebUI/Riode.WebUI/Areas/Admin/Views/Shared/_Side.cshtml
<ul id="sidebar_menu">
    <li class="">
        <a asp-controller="dashboard" asp-action="index" aria-expanded="false">
            <div class="nav_icon_small">
                <img src="~/uploads/images/img/menu-icon/1.svg" alt="">
            </div>
            <div class="nav_title">
                <span>Dashboard </span>
            </div>
        </a>

    </li>

    <li class="">
        <a asp-controller="dashboard" asp-action="invoice" aria-expanded="false">
            <div class="nav_icon_small">
                <img src="~/uploads/images/img/menu-icon/8.svg" alt="">
            </div>
            <div class="nav_title">
                <span>@SideBar.invoice </span>
            </div>
        </a>

    </li>
    <li class="">
        <a class="has-arrow" href="#" aria-expanded="false">
            <div class="nav_icon_small">
                <img src="~/uploads/images/img/menu-icon/Pages.svg" alt="">
            </div>
            <div class="nav_title">
                <span>@SideBar.pages</span>
            </div>
        </a>
        <ul>
            <li><a href="role_permissions.html">Role & Permissions</a></li>
            <li><a href="faq.html">FAQ</a></li>
            <li><a asp-controller="account" asp-action="login">Login</a></li>
            <li><a href="resister.html">Register</a></li>
            <li><a href="error_400.html">Error 404</a></li>
            <li><a href="error_500.html">Error 500</a></li>
            <li><a asp-controller="account" asp-action="forgot_pass">Forgot Password</a></li>
            <li><a href="gallery.html">Gallery</a></li>
            <li><a href="module_setting.html">Module Setting</a></li>
            <li><a href="Products.html">Products</a></li>
            <li><a href="Product_Details.html">Product Details</a></li>
            <li><a href="Cart.html">Cart</a></li>
            <li><a href="Checkout.html">Checkout</a></li>
        </ul>
    </li>

    <li class="">
        <a asp-controller="contacts" asp-action="index" aria-expanded="false">
            <div class="nav_icon_small">
                <img src="~/uploads/images/img/menu-icon/Mail_Box.svg" alt="">
            </div>
            <div class="nav_title">
                <span>@SideBar.contactpost </span>
            </div>
        </a>

    </li>
    <li class="">
        <a asp-controller="dashboard" asp-action="chat" aria-expanded="false">
            <div class="nav_icon_small">
                <img src="~/uploads/images/img/menu-icon/Mail_Box.svg" alt="">
            </div>
            <div class="nav_title">
                <span>@SideBar.chat </span>
            </div>
        </a>

    </li>
    <li class="">
        <a asp-controller="dashboard" asp-action="Layout" aria-expanded="false">
            <div class="nav_icon_small">
                <img src="~/uploads/images/img/menu-icon/forms.svg" alt="">
            </div>
            <div class="nav_title">
                <span>forms</span>
            </div>
        </a>

    </li>

    <li class="">
        <a asp-controller="brands" asp-action="index" aria-expanded="false">
            <div class="nav_icon_small">
                <img src="~/uploads/images/img/menu-icon/17.svg" alt="">
            </div>
            <div class="nav_title">
                <span>Brands</span>
            </div>
        </a>

    </li>
    <li class="">
        <a asp-controller="Categories" asp-action="index" aria-expanded="false">
            <div class="nav_icon_small">
                <img src="~/uploads/images/img/menu-icon/Mail_Box.svg" alt="">
            </div>
            <div class="nav_title">
                <span>Categories </span>
            </div>
        </a>

    </li>
    <li class="">
        <a asp-controller="products" asp-action="index" aria-expanded="false">
            <div class="nav_icon_small">
                <img src="~/uploads/images/img/menu-icon/Mail_Box.svg" alt="">
            </div>
            <div class="nav_title">
                <span>Products </span>
            </div>
        </a>

    </li>
    <li class="">
        <a asp-controller="faqs" asp-action="index" aria-expanded="false">
            <div class="nav_icon_small">
                <img src="~/uploads/images/img/menu-icon/Mail_Box.svg" alt="">
            </div>
            <div class="nav_title">
                <span>Faqs </span>
            </div>
        </a>

    </li>
    <li class="">
        <a asp-controller="BlogPosts" asp-action="index" aria-expanded="false">
            <div class="nav_icon_small">
                <img src="~/uploads/images/img/menu-icon/Mail_Box.svg" alt="">
            </div>
            <div class="nav_title">
                <span>Blog-Paylasimlar </span>
            </div>
        </a>

    </li>

</ul>